stages:
  - build
  - deploy

.ssh:
  before_script:
    - apt update && apt install -y openssh-client
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$DEPLOY_SSH_KEY")
    - mkdir -p ~/.ssh
    - echo "$WWW_HOST_KEY" > ~/.ssh/known_hosts

build:
  stage: build
  image: python:3
  tags:
    - shared
  script:
    - pip install --no-cache-dir pelican[markdown]
    - echo "Build website"
    - make htmldev
  artifacts:
    expire_in: 7 days
    paths:
      - output/

deploy:
  stage: deploy
  image: debian:latest
  tags:
    - sequential
  extends:
    - .ssh
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs:
    - build
  script:
    - apt update && apt install -y rsync && rm -rf /var/lib/{apt,dpkg,cache,log}/
    - echo "Deploying website..."
    - rsync -avz --delete output/ "$INSTANCE_NAME@$WWW_HOST:/var/www/$INSTANCE_NAME/html/"
    - echo "Website successfully deployed."
